version: 2.0
jobs:
  deploy:
    docker:
      - image: circleci/golang:1.8
    working_directory: /home/circleci/vault
    environment:
      DOCKER_IMAGE=mannimal/vault-cci

    steps:
      - checkout

      - setup_remote_docker
      # `deploy` a special `run` step that only gets run once
      #   even when parallelism is involved:
      #   https://circleci.com/docs/2.0/configuration-reference/#deploy
      - deploy:
          name: Install Docker client
          command: |
            set -x
            sudo curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz && sudo tar --strip-components=1

      - run:
          name: Build image
          command: docker build -t $DOCKER_IMAGE .

      - run:
          name: Tag and deploy image to docker hub
          command: |
            SHORT_SHA=$(git rev-parse --short HEAD)
            VERSION="0.1.${CIRCLE_BUILD_NUM}-${SHORT_SHA}"

            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$VERSION
            docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
            docker push $DOCKER_IMAGE

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
